name: cmake (snapshot)
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'What branch should be built?'
        required: true
        default: 'master'


jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  
          java-version: 11
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/googlecodecmake-maven-project
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Show versions
        run: |
          java --version
          mvn --version
      - name: Deploy
        run: mvn --batch-mode -V -e -U -Dsurefire.useFile=false -Ddeploy deploy
        env:
          MAVEN_USERNAME: foo
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            **/target/*.jar
